########## SECTION 1 - GENERAL SETTINGS ##########
########## Will probably never change
url: "https://kb.theobald-software.com"
baseurl: ""

# Name of website
title: Theobald Software Knowledge Base
# Short description of site
description: Theobald Software Knowledge Base contains tips, tricks and updates about our products

# For variables in the head such as for twitter cards
author:
  name: Theobald Software
  twitter: TheobaldSoftw

twitter:
  username: TheobaldSoftw
  card: summary

logo: /img/company/theobald_knowledgebase_logo.svg

# Only for SEO purposes, change the footer under _include/_footer as well if any of this changes.
social:
  name: Theobald Software
  links:
  - https://www.facebook.com/TheobaldSoftware
  - https://twitter.com/TheobaldSoftw
  - https://www.linkedin.com/company/theobald-software/
  - https://www.youtube.com/user/TheobaldSoftware
  - https://www.instagram.com/theobaldsoftware/

# TODO: please fill in
# google_site_verification:

algolia:
  application_id: '54P6URVM83'
  index_name: theobald-software-knowledgebase
  settings:
    attributesForFaceting: ['title','searchable(collection)', 'searchable(categories)', 'searchable(tags)', 'searchable(search-ignore)']
    searchableAttributes: ['title','unordered(content)','collection','description','categories','tags','search-ignore']

########## SECTION 2 - CONTENT ##########
########## Content is configurable here rather than in the html pages and include files
content:
  navbar-links:
    - title: "<strong>Online Help</strong>"
      url: "https://help.theobald-software.com"
    - title: "<strong>Troubleshooting Portal</strong>"
      url: "https://support.theobald-software.com/helpdesk/KB"
  homepage-title: "Browse through our knowledge articles"
  homepage-search-title: "Knowledge Base <br><small>How can we help?</small>"
  sidemenu-return-to-home: "Back to <strong>Homepage</strong> of Knowledge Base"
  sidemenu-return-to-section: "Back to overview for "
  sidebar-right-title: "On this page"
  search-no-results: "We didn't find any results for the search: "
  search-title: "Search the Knowledge Base"
  search-results: "Results"
  search-box-text: "Search..."
  section-page-default-explanation: "The following knowledge base articles are in this section."
  news-overview-page-default-explanation: "All new articles can be found here."

########## SECTION 3 - COLLECTION CONFIGURATIONS ##########
########## Languages can easily be added this way.
##########  see the readme file for more information regarding that,
##########  requires more than just adding a language here.
collections_dir: content
collections:
  general:
    output: true
    name: 'General'
    weight: 1
  sap:
    output: true
    name: 'SAP'
    weight: 2
  xtract-is:
    output: true
    name: 'Xtract IS'
    weight: 3
  xtract-universal:
    output: true
    name: 'Xtract Universal'
    weight: 4
  xtract-for-alteryx:
    output: true
    name: 'Xtract for Alteryx'
    weight: 5
  yunio:
    output: true
    name: 'yunIO'
    weight: 6
  board-connector:
    output: true
    name: 'BOARD Connector'
    weight: 7
  erpconnect-general:
    output: true
    name: 'ERPConnect - General'
    weight: 8
  erpconnect-samples:
    output: true
    name: 'ERPConnect - Samples'
    weight: 9
  archive:
    output: true
    name: 'Archive'
    weight: 10
  version-history:
    output: true
    name: 'Version History'
    weight: 11
  posts:
    output: true


########## SECTION 4 - OTHER SETTINGS ##########
########## Be careful with changes to these settings, as it could break things.
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-paginate
# sass (styling)
sass:
  sass_dir: css/scss
  style: compressed
# Default YAML values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      image: /img/company/theobald_knowledgebase_logo.svg
      lang: "en_GB"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /img/company/theobald_knowledgebase_logo.svg
      lang: "en_GB"
      is_post: true
# Exclude
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile
  - .idea/workspace.xml
  - vendor

########## SECTION 5 - TRACK SETTINGS ##########
# GA gatg.js ID
#gtag: ""
# GA ID
#google_analytics: ""
# GTM ID
#gtm: ""
# Matomo site ID
matomo_analytics: "3"
